### ISSUE TITLE
[Epic] Solver Slippage V2

### ISSUE THREAD

**Issue by bh2smith** [cowprotocol/solver-rewards#177]
Based on [Specification Documentation](https://docs.google.com/document/d/15mByvoI7EQ-wFAM9QkDCMnjA4AVjbG0_G0GdirziGBM/edit#heading=h.9pv5om83u7ef)

We layout a top-down approach plan for this repo. Development will take place in a "Feature Branch" and [this](https://github.com/cowprotocol/solver-rewards/pull/184) is an open PR containing an aggregation of all changes.

## Phase 1:  Acquiring Internalized Transfers

Note that a Proof of Concept has already been implemented in python [here](https://github.com/cowprotocol/dune-sync/pull/22/files) and can be used for reference when reviewing (cc @gentrexha)

- [x] Setup Initial DB Migration (#178)
- [x] Basic Tenderly Web3 Action For Settlement Events (#181)
- [x] Add Models & Parsing Logic to WebHook (#182)
- [x] Parse Trades and Transfers from Settlement Transaction Receipts. #193
- [x] Use Action to Insert SettlementEvents to DB (#185)
- [x] Fetch winning settlement from orderbook API by txHash (#220)
- [x] Simulate Full Call Data from Winning Settlement (#227)
- [x] Parse Simulation Results (#228)
- [x] Parse transfer events from simulated transaction (#229)
- [x] Aggregate transfers with accumulator as "imbalance" (#233)
- [x] Token Imbalance Arithmetic (#234)
- [x] **Project Milestone** Compute Internalized Imbalance as `Full - Actual` (#231)
- [x] Insert `InternalizedImbalances` into DB (#242)
- [x] Tie together all functionality as a single workflow to call from within the web-hook (#261)
- [x] Introduce Data dumping ground for unconfirmed transactions (#271)
- [x] Adjust pipeline to account for finalized and unconfirmed transactions (#272)
- [x] Extend Tx Receipt so that Settlement Log index is block-wise not transaction-wise. (#275)
- [x] Mark Processed (#276)
- [x] Deploy to Staging DB ([announcement](https://cowservices.slack.com/archives/C0361CCTFD5/p1683808527703169))
- [x] Bug - #281
- [x] Bug - #279
- [x] MAIN BRANCH CONCLUDING PHASE 1 (#184)

## Phase 2:  Dune Sync
- [x] Obtain a Production DB and Deploy Phase 1 to production ([slack](https://cowservices.slack.com/archives/C036PMLUPQF/p1684155889714619))
- [ ] Configure auto deployments.
- [x] Inject data into dune community sources. This is part of a different project -- namely [dune-sync](https://github.com/cowprotocol/dune-sync) (https://github.com/cowprotocol/dune-sync/pull/37)
- [ ] This project will need to be able to to determine if there is any missing data before sync. 
- [ ] If something is missing, it should be able to trigger the pipeline "en masse" (for a collection of `txHashes`).

## Phase 3: Refactor Slippage Query
- [x] Replace [this portion](https://github.com/cowprotocol/solver-rewards/blob/c7e9c85706decb1a1be28d639ee34e35646bca50/queries/dune_v2/period_slippage.sql#L239-L309) of the slippage query with internalized transfer data. (#259)

## Additional TODOs & Cleanup

- [x] #226
- [x] #230 
- [x] #232
- [x] #235
- [ ] #236
- [x] #237
- [x] #246
- [x] #245
- [x] Manual mass application of Phase 1 (i.e. without web-hook trigger) and ensure idempotency. (#244)
- [ ] #274

## Follow Up Tasks

- [ ] Migrate primary functionality of Phase 1 into an AWS lambda and deploy. This will reduce attack surface by not exposing DB credentials to a third party service. Will also give us a gateway to more involved pipeline projects. Prototype exists [here](https://github.com/bh2smith/web3-event-etl/blob/main/tenderly/actions/src/lambda.ts)
- [ ] ... probably more stuff.

**Comment by bh2smith** [comment]
Some very helpful Proof of Concept Code can be found

- [A Typed Python Implementation](https://github.com/cowprotocol/dune-sync/pull/22) of the full pipeline excluding DB writes.
- [Components of the Grand Scheme](https://github.com/bh2smith/web3-event-etl/) including Tenderly Action that writes to DB & invokes AWS lambda.

**Comment by fleupold** [comment]
I think one open design decision is what data we should store in our database (future data warehouse). I believe @olgafetisova was in favor of ingesting the raw transaction receipts/simulation results and then run the slippage computation based on another script on our database:

- Tenderly Simulation Result --> DB --> Script to compute slippage --> DB (or unmaterialized view)
- Tenderly Simulation Result --> Script to compute slippage --> DB

The latter has the advantage IMO that it would make the script easily reproducible by third parties (all they need is tenderly access, no need to access our DB). On the other hand, having one script ingesting the simulation result and another script computing the slippage based off that splits responsibilities and may allow us more easily replace the tenderly dependency (e.g by our own node simulation) later on. Also, if there are other use cases that would use those simulation results, we wouldn't have to run the simulation multiple times.

**Comment by bh2smith** [comment]
Thanks Felix, these are all very good points to consider and the avenue I have been going is definitely the second. I want to point out that you keep mentioning "Script to compute slippage" as if that is what we are doing here... however this project is aimed at computing "internalized token imbalance". If that is not your understanding, then this should be aligned (maybe you want to read the introduction section of the specification). We can easily change gears if necessary, but the goal here currently is to replace the approximation being made in the existing slippage query. Long term, we would transition this into a fully internal slippage computation.


> raw transaction receipts/simulation results 

I am very much in favour of saving simulations and storing their IDs on our side, but each simulation is a VERY LARGE JSON blob that I don't think we should be keeping on our side (at least not without reducing it by pruning unnecessary parts).


> replace tenderly dependency

The project has been written in a way (with an interface `TxSimulator` -- cf #227) that should already make it easy enough to swap out our `TenderlySimulator`

**Comment by fleupold** [comment]
> you keep mentioning "Script to compute slippage" as if that is what we are doing here...

I was judging from the title of this EPIC ("Solver Slippage v2"), that the final deliverable of this EPIC was a script to compute more accurate solver slippage. On the way there the goal is to pioneer and build the foundation for our data warehouse infra.

**Comment by bh2smith** [comment]
## Foreseeable Issues & Complications 

1. This "uninternalizedCallData" which this project requires may not be accessible upon solver-driver colocation. This would essentially kill this project (in ~2-3 months)
2. Going back in time to recover historical data will likely result in rate limiting.


### Workflow Failure Points

- [ ] Each settlement requires a passing simulation to yield "correct" results. When simulation fails? Try `simBlock + 1`? Then what? We could treat it as if there were no internalized transfers and "let it slide"
- [ ] What happens when the array of solutions has length zero?
- [ ] what to do when the actual settlement solver does not agree with the winning solver from the competition?

**Comment by bh2smith** [comment]
>  final deliverable of this EPIC was a script to compute more accurate solver slippage

Yes this is correct, but does not mention computing it from our own database. Rather an adaptation of our existing query.

> On the way there the goal is to pioneer and build the foundation for our data warehouse infra.

In fact this is already happening. Its just that we are not just gonna start pumping a bunch of bloat into a database right from the start. It will be very small and compact representation of what we need to "compute accurate slippage"

**Comment by olgafetisova** [comment]
As agreed earlier with Ben, he is going to give us a presentation with the choices that have been already made and the actual state of the project, additionally, he is going to host a discussion session on the open questions so that all the reviewers of the project are aligned on the next steps.
