### ISSUE TITLE
Clean up rewards code

### ISSUE THREAD

**Issue by fhenneke** [cowprotocol/solver-rewards#452]
- [x] Make command line arguments part of config (e.g. #474)
- [x] Restructure main payout function #435 
- [ ] Combine database functionality #459 
- [ ] Make command line arguments more consistent #494 (and fix docs #495)
